PRODUCT_VERSION_MAJOR = 13
PRODUCT_VERSION_MINOR = 0

# Set all versions
GUMIHO_BUILD_TYPE ?= UNOFFICIAL
GUMIHO_FLAVOR := Tiramisu
GUMIHO_CODE := 1.0
ANDROID_CODE := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

# Internal version
LINEAGE_VERSION := GumihoAOSP-$(GUMIHO_CODE)-$(LINEAGE_BUILD)-$(GUMIHO_BUILD_TYPE)-$(GUMIHO_VARIANT)-$(shell date +%Y%m%d)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(LINEAGE_VERSION_SUFFIX)
